@startuml
start
:Get endpoint information;
:Get service call
information;
:Build relationship
between client
and service call;
:Check untested client;
:Generate client code;
:Generate MPD file;
stop
@enduml