@startuml
scale 2
start
:Get Client Information;
:Get Service Call
Information;
:Build Relationship
between Client
and Service Call;
:Check Untested Client;
:Generate Client Code;
:Generate MPD file;
stop
@enduml