version: '2'
services:
  mongo:
    image: mongo:3.4.2
    ports:
    - "27017:27017"
  codegen:
    build: ../mgp-codegen
    ports:
      - "3001:3001"
  bdd:
    build: ../mgp-bdd
    ports:
      - "3005:3005"
  neo:
    image: neo4j:3.1.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=4g
      - NEO4J_dbms_memory_heap_maxSize=8g
