version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  codegen:
    build: ../mgp-codegen
    ports:
      - "3001:3001"
  bdd:
    build: ../mgp-bdd
    ports:
      - "3005:3005"
  neo:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none