spring:
  application:
    name: mpgback
  data:
    mongodb:
      database: mpg
      host: ${MONGO_DB:localhost}
    neo4j:
      uri: ${NEO4J_DB:http://localhost:7474}
      username: neo4j
      password: neo4jneo4j

mpg:
  codegen:
    url: ${CODEGEN_HOST:http:/localhost:3000/}