spring:
  application:
    name: mpgback
  data:
    mongodb:
      database: mpg
      host: ${mpg_DB_HOST:localhost}
    neo4j:
      uri: http://localhost:7474
      username: neo4j
      password: neo4jneo4j