@startuml
actor User as user
participant "MGP React App" as mgpr
participant "MGP Service" as mgps
participant "BDD Parser\nService" as bps

user -> mgpr: View\ndependency\ngraph
activate mgpr
mgpr -> mgps: Check graph\ndata update
activate mgps
mgps -> bps: \nUpdate UAT project
activate bps
bps --> mgps: Return result
deactivate bps
mgps -> bps: \nGet UAT information
activate bps
bps --> mgps: Return result
deactivate bps
mgps -> mgps: \nBuild service\ndependency graph
mgps --> mgpr: Return result
deactivate mgps
mgpr -> mgps: Get dependency\ngraph data
activate mgps
mgpr <-- mgps: Return data
deactivate mgps
mgpr --> user: Dispaly
deactivate mgpr

@enduml