@startuml
actor User
participant "MGP React App" as A
participant "MGP Service" as B
participant "Cucumber Report\nService" as C

User -> A: View Report
activate A

A -> B: Request report data
activate B


B --> A: Return data
deactivate B

A --> User: Display
deactivate A


User -> C: View cucumber report
activate C

C -> B: Request the \ncucumber report
activate B


B --> C: \tReturn report
deactivate B
C --> User: Return page
deactivate C


@enduml