@startuml
actor User
participant "MGP React App" as A
participant "MGP Service" as B
participant "Service Call Code\nGenerator Service" as C

User -> A: View dependency\ngraph
activate A

A -> B: Request for endpoint\ninformation
activate B

B -> C: Get endpoint call\nexample code
activate C
B <-- C: Return data
deactivate C

B --> A: Return data
deactivate B

A --> User: Display
deactivate A
@enduml
