@startuml
scale 2
start
:Generate a MPD\nfrom a microservice project;
:Upload to MGP;
:View annotations from website;
-> An endpoint is used \nby the scenario;
if() then(yes)
:Write BDD scenario's annotation;
:BDD git project is parsed by BPS;
:Generate dependency graph;
else (no)
stop
endif
stop
@enduml
