@startuml
scale 2
'left to right direction
Actor User as u
rectangle Jenkins as j

rectangle "Pact Broker System" {
    rectangle "Pact Broker" as pb
    database "Postgresql " as pg
    pb -l-> pg
}
rectangle "Microservice Project" as mp {
    artifact MCA as mca
}
rectangle "BDD Project" as bddp {
    rectangle "Regression\nTest Agent" as bta
}
rectangle "Service Test Project" as stp {
    rectangle "Regression\nTest Agent" as sta
}
file MPD as mpd
rectangle "MGP"{
    rectangle Haproxy as ha
    rectangle "MGP React App" as ra
    rectangle "Service Call\nCode Generator\nService" as cg
    rectangle "BDD\nParser\nService" as bp
    rectangle "Cucumber\nReport\nService" as cr
    rectangle "MGP Service" as ab
    database "Neo4j" as n
    database "MongoDB" as m
    ha -d-> ra
    ha -> cr
    ha -d-> ab
    ab -d-> n
    ab -d-> m
    ab -> cg
    ab -d-> bp
}
j .> pb
j .> sta
j .> bta
ha <. sta
ha <. bta
bp .u.> bddp
u .d.> ha
j .d.> ha
ab .d.> pb
j .d.> mp
mca -d-> mpd
j .> mpd

stp -[hidden]d-> bddp
'bddp -[hidden]-> pb
@enduml
