@startuml
start
:Get Invocation Chain Group;
:Check All Invocation Chain Path;
-> A path has two endpoint\nowned by the same service;
if() then(yes)
:Check the Path has the same\nEndpoint exist more than once;
if() then(yes)
:Mark the group is\nStrong Cyclicity;
else(no)
:Mark the group is\nWeek Cyclicity;
endif
else(no)
endif
stop
@enduml