@startuml
scale 2
start
:Get invocation chain group;
:Check all invocation chain path;
-> A path has two endpoint\nowned by the same service;
if() then(yes)
:Check the path has the same\nendpoint exist more than once;
if() then(yes)
:Mark the group is\nstrong cyclic dependency;
else(no)
:Mark the group is\nweek cyclic dependency;
endif
else(no)
endif
stop
@enduml
