@startuml
start
:Web Get Data;
:HTTP POST Check update;
partition Server {
    :Get Data From Pact Broker;
    :Update BDD project;
    if (BDD project Has update?) then (yes)
        :Build Neo4j Graph;
    else (no)
    endif
}
fork
    :HTTP Get D3 Data;
    partition Server {
        :Get Visual Data;
        :Return Data;
    }
fork again
    :HTTP Get Service Information;
    partition Server {
        :Get Data;
        :Return Data;
    }
fork again
    :Get Service Call Inforamtion;
    partition Server {
        :Get Pair of \nConsumer and Provider;
        if (No Pact Files?) then (yes)
            :Match Pact file to Pair of\nConsumer and Provider;
        else (no)
        endif
        :Return Data;
    }
fork again
    :Get Endpoint Inforamtion;
    partition Server {
        :Get Pact Data;
        :Return Data;
    }
fork again
    :Get Scenario Inforamtion;
    partition Server {
        :Get BDD Data;
        :Return Data;
    }
end fork
stop
@enduml