@startuml
left to right direction
actor User as user
rectangle "Jenkins Pipeline" as jp
rectangle "Pact Broker" as pb

rectangle "MGP" {
rectangle "Service Call\nCode Generator\nService" as cg
    rectangle "UAT\nAnalyzer\nService" as ua
	rectangle "MGP React App" as react


    rectangle "MGP Service" as mgp {
        rectangle "Controller" as con
        rectangle "Regression\nPicker" as rp
        rectangle "Graph\nService" as gs
        rectangle "MPD\nReader" as mr
        rectangle "Service Call\nCode Generator\nFacade" as cgf
        rectangle "UAT\nFacade" as uf
        rectangle "Pact Broker\nFacade" as pbf
        rectangle "Test Reader" as tr
        database Neo4j as neo
        database MongoDB as mon
    }

    react .> con

    con -d-> rp
    con -d-> gs
    con -d-> mr
    con -d-> cgf
    con -d-> uf
    con -d-> pbf
    con -d-> tr

    rp -d-> neo
    gs -d-> neo
    mr -d-> neo
    uf -d-> neo

    mr -d-> mon
    cgf -d-> mon
    uf -d-> mon
    pbf -d-> mon
    tr -d-> mon
}

jp .d.> con
jp .[hidden].> react
user .> con
user .> react
cgf .> cg
uf .> ua
pbf .> pb

neo -[hidden]> cg
neo -[hidden]> ua
neo -[hidden]> pb
@enduml