@startuml
|Developement|
start
:Developer update project;
:Jenkins pipeline start;
|Unit Test|
:Execute unit test;
:Upload MPD\nfile to MGP;
-> Unit test result?;
if () then (fail)
    stop
else (pass)
    :Upload pact DSL\nfile to Pact Broker;
    |Service Test|
    :Execute service test;
    :Upload \nservice test \nresult to MGP;
    -> Service test result?;
    if () then (fail)
        stop
    else(pass)
        |UAT|
        :Execute UAT;
        :Upload UAT result to MGP;
    endif
    stop
endif
@enduml