@startuml
'scale 1.5
start
:Get invocation chain group;
:Find the paths contain\nthe updated service;
:Filter out the service is after\nthe target service two level;
:Calculate test priority scrore;
->Run service test?;
if() then (yes)
    :Pair the consumer and\n provider services;
    :Pick the pact file;
else (no)
    :Generate the Cucumber\n test annoation;
endif
:Return data;
stop
@enduml
