@startuml
scale 1.5
start
:Get Invocation Chain Group;
:Find the paths contain\nthe updated service;
:Filter out the Service is after\nthe target service two level;
->Run service test?;
if() then (yes)
    :Pair the consumer and\n provider Services;
    :Pick the pact file;
else (no)
    :Generate the Cucumber\n test annoation;
endif
:Return Data;
stop
@enduml