@startuml
scale 1.5
rectangle "A Microservice Project" as mp
rectangle "Jenkins Pipeline" as jp
rectangle "BDD project" as bp
rectangle "Pact Broker" as pb
actor user

rectangle {
	rectangle "MCA" as mca
	rectangle "MGP"as mgp
	rectangle "UAT Parser" as uatp
	rectangle "Code Generator" as d

	rectangle "MPD" as mpd

	mca -r-> mpd
	mgp -> uatp
	mgp -> d
}

mpd.>jp
mca .> mp
jp .> mca
jp .> mgp
uatp .> bp
mgp .> pb
user .> mgp

@enduml