@startuml
scale 2
'skinparam backgroundcolor transparent
left to right direction
rectangle "A Microservice Project" as mp
rectangle "Jenkins Pipeline" as jp
rectangle "BDD project" as bp
rectangle "Pact Broker" as pb
actor User as user

rectangle "MGP" as t {
	rectangle "Regression\nTest Agent" as ta
	rectangle "MCA" as mca
	rectangle "MGP\nReact APP"as mgpa
	rectangle "MGP\nService"as mgp
	rectangle "BDD Parser\nService" as uatp
	rectangle "Service Call\nCode Generator\nService" as d
	rectangle "Cucumber Report\nService" as crs

	file "MPD" as mpd

	mca -> mpd
	mgp -d-> uatp
	mgp -d-> d
	mgpa -d-> mgp
	crs -d-> mgp
	ta -d-> mgp
}

jp.>ta
jp.>mpd
mca .u.> mp
jp .d.> mca
jp .d.> mgp
uatp .> bp
mgp .d.> pb
user .d.> mgpa
user .d.> crs
uatp .[hidden]d.> pb
uatp .[hidden]d.> bp
@enduml
